// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7gWj8tS-nNhdZvyWIzbopW3yYtZlUMgI',
    appId: '1:589726044623:web:35eea3ce420711358102ba',
    messagingSenderId: '589726044623',
    projectId: 'howzy-5ddd9',
    authDomain: 'howzy-5ddd9.firebaseapp.com',
    storageBucket: 'howzy-5ddd9.firebasestorage.app',
    measurementId: 'G-J5MP80SS10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaWvVOYOCsjcvd7mKmV24izOSz5pmMuBw',
    appId: '1:589726044623:android:a27048493ce739c28102ba',
    messagingSenderId: '589726044623',
    projectId: 'howzy-5ddd9',
    storageBucket: 'howzy-5ddd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPGAlE0wC5G8rTp3yEeS5bnmx3QjQlVe8',
    appId: '1:589726044623:ios:63145e746ccc3e198102ba',
    messagingSenderId: '589726044623',
    projectId: 'howzy-5ddd9',
    storageBucket: 'howzy-5ddd9.firebasestorage.app',
    iosBundleId: 'com.example.frontendUi',
  );
}
