name: Firebase Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  FLUTTER_VERSION: "3.41.4"

jobs:
  build-and-distribute-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:589726044623:android:a27048493ce739c28102ba
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          file: build/app/outputs/flutter-apk/app-release.apk
          groups: testers
